// Generated by https://quicktype.io

// copy the raw json file from https://grandcircusco.github.io/demo-apis/blog-posts.json
// come to this blog.ts file --> erase everything --> hit ( ctrl + shift + P ) to open search bar and then search for : Paste JSON as code 
// give name (e.g. Blog ) in asked field and it will generate interface


export interface Blog {
    title:    string;
    language: string;
    posts:    Post[];
}

export interface Post {
    title:   string;
    author:  string;
    content: string;
    date:    string;
    tags:    string[];
}
